# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate files
        run: |
          sudo apt-get install pandoc
          ./gen_cdb_json.sh
          ./gen_doc_html.sh
      - name: contentdb file production
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: .cdb.json
      - name: Documentation production
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: doc/api.html